/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package it.unibo.disiBuilderPlugin

import org.gradle.api.Project
import org.gradle.api.Plugin
import unibo.disi.builder.generator
import unibo.disi.builder.generatorQak

/**
 * A simple 'hello world' plugin.
 */
class DisiBuilderPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("buildDisi") { task ->
            task.doLast {
                val s = generator.genFilePathName("pluto")
                println("DisiBuilderPlugin | generates the path-name: $s ")
            }
        }

        project.task("buildActors"){
            it.doLast {
                println("DisiBuilderPlugin | generates Qak ")
                generatorQak.genQak( "./src", "demoactor")
            }
        }
    }
}
