/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package it.unibo.disiBuilderPlugin

import org.gradle.api.Plugin
import org.gradle.api.Project
import unibo.disi.builder.*


/**
 * A simple 'hello world' plugin.
 */
class DisiBuilderPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("buildDisiTest") { task ->
            task.doLast {
                val s = genUtils.genFilePathName("test")
                println("DisiBuilderPlugin | generates the path-name: $s ")
            }
        }
/*
        project.task("buildQakSystem"){
            it.doLast {
                println("DisiBuilderPlugin | generates Qak ")
                GeneratorQak.genQak("./src", "demoactor")
            }
        }
*/
        project.tasks.register("projectInfo", ProjectInfoTask::class.java) {
            it.doFirst {
                println("DisiBuilderPlugin | projectInfo ")
            }
        }

        project.tasks.register("buildQakSystem", BuildQakSystemTask::class.java ){
            it.doFirst {
                println("DisiBuilderPlugin | buildQakSystem ")
            }
        }

        project.tasks.register("buildDisi", BuildActorTask::class.java ){
            it.doFirst {
                println("DisiBuilderPlugin | buildDisi ")
            }
        }

    }
}
