version: '3'
services:
  wenv:
    image: virtualrobotdisi:1.0
    ports:
      - 8090:8090
      - 8999:8999/tcp
  vrobotclient:
    image: vrobotclient:1.0
    depends_on:
      - wenv
    
## docker-compose run --service-ports wenv
## docker-compose run --service-ports vrobotclient  ATTIVA ANCHE wenv