/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.7.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    //id("org.jetbrains.kotlin.jvm") version "1.3.72"
    //id("org.jetbrains.kotlin.jvm") version "1.4.30-M1"
    //`kotlin-dsl`
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("unibo.disi.builder") version "1.0"

}

/*
project.plugins.forEach() {
    println( it )
}
*/

task("showClasspath")  {
    doLast {
        buildscript.configurations.forEach{ println( it.allArtifacts ) }
    }
}

task("buildDemo0"){
    doLast{
        val v = unibo.disi.builder.Generator.genCodeFromModel("demo0")
    }
}
task("buildDemo1"){
    doLast{
        val v = unibo.disi.builder.Generator.genCodeFromModel("demo1")
    }
}

task("hello"){
    doLast(){
        println("hello testBuilder")
    }
}

task<unibo.disi.builder.BuildActorTask>("yyy"){
    prefix   = "BuildActorTask test ..."
    actorModel="yyy"
}
/*
task("enterDemoMode", Exec::class) {
    group      = "demoMode"
    executable = "adp"
    args = listOf("shell", "settings", "put", "global", "sysui_demo_allowed", "1")
}
*/
task<Exec>("echoNat") {
    workingDir("$projectDir")
    if (System.getProperty("os.name").toLowerCase().contains("windows")) {
        //commandLine("cmd", "/c", "echo", "my name is nat")
        commandLine("cmd", "/c", "gradle", "eclipse")
    } else {
        commandLine( "sh", "-c", "echo", "nico")
    }
}

/*
ADDED AFTER buildSrc

//val compileClasspath by configurations.creating

task<CommonTask>("ct"){
    println("................... ct " )
    actorModel="demo1"
}
*/



/*
//A LOCALLY DEFINED PLUGIN

open class DisiGenTask : DefaultTask() {
    @TaskAction
    fun buildActorCode() {
        println("DisiGenTask START")
        //generator.genCodeFromModel("demo0")
    }
}
tasks.register<DisiGenTask>("genactor")


task<DisiGenTask>("disiBuild"){
    println("................... disiBuild " )
    actorModel="demo0"

}*/
/*
//POWERSHELL JUST TO KNOWN ...
gradle properties |
    Where-Object { $_ -match '(?<=^plugins: \[).*(?=\])'; } |
    Out-Null;
$Matches.Values -split ", " |
    ForEach-Object { ($_ -split "@")[0]; }
 */