package unibo.disi.builder

object generatorActorMsgDrivenCode {

    fun gen( actorName: String) : String{
        val dollar = "$"
        val packageName =  "${Generator.packagelogo}/$actorName".replace("/",".")
        return """
/* Actor msg-driven Generated by AN DISI Unibo */
package $packageName
import kotlinx.coroutines.*
import kotlinx.coroutines.channels.actor
import kotlinx.coroutines.channels.SendChannel

var senderActor   : SendChannel<String>?  = null
var receiverActor : SendChannel<String>?  = null
val cpus = Runtime.getRuntime().availableProcessors(); 

fun curThread() : String { 
	return "thread=$dollar{Thread.currentThread().name} / nthreads=$dollar{Thread.activeCount()}" 
}
               
fun startReceiver( scope : CoroutineScope ){
	receiverActor = scope.actor<String> {   
		println("receiverActor STARTS")
		var msg = channel.receive()
		while( msg != "end" ){ 	//message-driven
			println("receiverActor receives "+ msg)
			msg = channel.receive()
		}
		println("receiverActor ENDS")
	}
}
 
fun startSender( scope : CoroutineScope){
	senderActor = scope.actor {  
		//actor is a coroutine builder (dual of produce)
		println("senderActor   STARTS")
 		receiverActor!!.send("Hello1")
		delay(250)
 		receiverActor!!.send("Hello2")
		delay(250)
		receiverActor!!.send("end")
		println("senderActor   ENDS")
 	}
} 

@kotlinx.coroutines.ObsoleteCoroutinesApi
@kotlinx.coroutines.ExperimentalCoroutinesApi

fun main() = runBlocking{
    println("BEGINS CPU=$dollar{cpus}"   )
 	startReceiver( this )
	startSender( this )
    println("ENDS $dollar{curThread()}"   )
}
"""
    }

}//generatorActorMsgDrivenCode