package unibo.disi.builder

object GeneratorActorFsmCode {

    fun gen( actorName: String) : String{
        val dollar ="$"
        val packageName =  "${Generator.packagelogo}/$actorName".replace("/",".")
        return """
 /* Actor msg-based Generated by AN DISI Unibo */ 
package $packageName
import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class $actorName(name: String, scope: CoroutineScope) : ActorBasicFsm( name, scope ){
	override fun getInitialState() : String{
		return "init"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return {
				state("init") {
					action {
						println("$actorName | STARTS")
                        //forward a dispatch to itself
                        forward("msg1", "msg1(autoHello)" ,"$actorName" ) 
						//TODO 
					}
					transition( edgeName="goto",targetState="waitinput", cond=doswitch() )	 
				}
 				state("waitinput") {
					action {
                        stateTimer = TimerActor("timer_waitinput", 
                             scope, context!!, "local_tout_${actorName}_waitinput", 1000.toLong() )
					}
                    transition(edgeName="t00",targetState="handleTimeOut", cond=whenTimeout("local_tout_${actorName}_waitinput")) 
					transition(edgeName="t01",targetState="handleDispatch",cond=whenDispatch("msg1"))
					transition(edgeName="t02",targetState="handleRequest", cond=whenRequest("r1"))
					transition(edgeName="t03",targetState="handleAlarm",   cond=whenEvent("alarm"))
				}		
		
				state("handleDispatch") {    //this:State
					action {     //it:State
                        println("$actorName in handleDispatch")
						println("${dollar}name in ${dollar}{currentState.stateName} | ${dollar}currentMsg")
						if( checkMsgContent( Term.createTerm("msg1(ARG)"), Term.createTerm("msg1(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("$actorName msg1:msg1(${dollar}{payloadArg(0)})")
								//delay(1000) 
						}
					}
					 transition( edgeName="goto",targetState="waitinput", cond=doswitch() )
				}	 

				state("handleRequest") { //this:State
					action { //it:State
						println("$actorName in handleRequest")
						println("${dollar}name in ${dollar}{currentState.stateName} | ${dollar}currentMsg")
					}
					 transition( edgeName="goto",targetState="waitinput", cond=doswitch() )
				}	 

				state("handleAlarm") { //this:State
					action { //it:State
						println("$actorName in handleAlarm")
						println("${dollar}name in ${dollar}{currentState.stateName} | ${dollar}currentMsg")
					}
					 transition( edgeName="goto",targetState="s1", cond=doswitch() )
				}	 


                state("handleTimeOut") { 
					action { 
						println("${actorName} TIME-OUT")
						terminate(0)
					}
				}	
				state("endOfWork") { 
					action { 
						println("${actorName} BYE")
						terminate(0)
					}
				}	 			
			}
 
		}
}
"""
    }

}