package unibo.disi.builder

object GeneratorActorMsgBasedCode {

    fun gen( actorName: String) : String{
        val packageName =  "${Generator.packagelogo}/$actorName".replace("/",".")
        return """
 /* Actor msg-based Generated by AN DISI Unibo */ 
package $packageName
import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class $actorName(name: String, scope: CoroutineScope) : ActorBasicFsm( name, scope ){
	override fun getInitialState() : String{
		return "init"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return {
				state("init") {
					action {
						println("$actorName | STARTS")
						//TODO 
					}
					transition( edgeName="goto",targetState="waitinput", cond=doswitch() )	 
				}
 				state("waitinput") {
					action {
                        stateTimer = TimerActor("timer_waitinput", 
                             scope, context!!, "local_tout_demoactor_s1", 1000.toLong() )
					}
                    transition(edgeName="t00",targetState="handleTimeOut",cond=whenTimeout("local_tout_demoactor_waitinput")) 
					transition(edgeName="t01",targetState="endOfWork",cond=whenEvent("end"))
					transition(edgeName="t02",targetState="endOfWork",cond=whenTimeout("local_tout_${actorName}_waitinput"))   
				}			
				state("endOfWork") { 
					action { 
						println("${actorName} BYE")
						terminate(0)
					}
				}	 			
			}
 
		}
}
"""
    }

}