/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package provaPlugin

import org.gradle.testkit.runner.BuildResult
import java.io.File
import org.gradle.testkit.runner.GradleRunner
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'provaPlugin.greeting' plugin.
 * See https://docs.gradle.org/current/userguide/test_kit.html
 * See https://docs.gradle.org/current/javadoc/org/gradle/testkit/runner/package-summary.html
 */
class ProvaPluginPluginFunctionalTest {
    @Test fun `can run task`() {
        // Setup the test build
        val projectDir = File("build/functionalTest")
        projectDir.mkdirs()
        projectDir.resolve("settings.gradle").writeText("")
        projectDir.resolve("build.gradle").writeText("""
            plugins {
                id('provaPlugin.greeting')
            }
        """)

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("greeting")
        runner.withProjectDir(projectDir)
        val result = runner.build();  //result org.gradle.testkit.runner.BuildResult
        println(" .... ${result.output}") //The textual output produced during the build.

        val tasks = result.getTasks()
        tasks.forEach{ v -> println("task: ${v}")}

        // Verify the result
        assertTrue(result.output.contains("Hello from plugin 'provaPlugin.greeting'"))

    }
}
