/* Generated by AN DISI Unibo */ 
package it.unibo.provaactor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Provaactor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("provaactor STARTS")
					}
					 transition( edgeName="goto",targetState="s1", cond=doswitch() )
				}	 
				state("s1") { //this:State
					action { //it:State
						println("demo in s1")
						stateTimer = TimerActor("timer_s1", 
							scope, context!!, "local_tout_provaactor_s1", 1000.toLong() )
					}
					 transition(edgeName="t00",targetState="handleTimeout",cond=whenTimeout("local_tout_provaactor_s1"))   
					transition(edgeName="t01",targetState="handleDispatch",cond=whenDispatch("msg1"))
					transition(edgeName="t02",targetState="handleRequest",cond=whenRequest("r1"))
					transition(edgeName="t03",targetState="handleAlarm",cond=whenEvent("alarm"))
				}	 
				state("handleTimeout") { //this:State
					action { //it:State
						println("provaactor handleTimeout")
					}
				}	 
				state("handleDispatch") { //this:State
					action { //it:State
						println("provaactor in handleDispatch")
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("msg1(ARG)"), Term.createTerm("msg1(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("provaactor msg1:msg1(${payloadArg(0)})")
								delay(1000) 
						}
					}
					 transition( edgeName="goto",targetState="s1", cond=doswitch() )
				}	 
				state("handleRequest") { //this:State
					action { //it:State
						println("provaactor in handleRequest")
						println("$name in ${currentState.stateName} | $currentMsg")
					}
					 transition( edgeName="goto",targetState="s1", cond=doswitch() )
				}	 
				state("handleAlarm") { //this:State
					action { //it:State
						println("provaactor in handleAlarm")
						println("$name in ${currentState.stateName} | $currentMsg")
					}
					 transition( edgeName="goto",targetState="s1", cond=doswitch() )
				}	 
			}
		}
}
