/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package it.unibo.disiBuilderPlugin

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'it.unibo.disiBuilderPlugin.greeting' plugin.
 */
class ItUniboDisiBuilderPluginPluginTest {
    /*
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("it.unibo.disiBuilderPlugin.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }*/
}
