/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.7.1/userguide/multi_project_builds.html
 */
pluginManagement {
    println("SETTINGS pluginManagement ...")
    repositories {
        maven(url = "../uniboRepos/maven-repo")       
        flatDir { dirs("../unibolibs") } //REQUIRED FOR THE unibo plugins
        gradlePluginPortal()
    }
} 

 

rootProject.name = "provaDisiBuilder"
//include("app")
