{
  "formatVersion": "1.1",
  "component": {
    "group": "unibo.disi",
    "module": "plugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6x5at7ruybcifd4fubi3cezuni"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.jar",
          "url": "plugin-1.0.jar",
          "size": 40294,
          "sha512": "70124f3e7799260e93bab423bc0a9fa318276204da9e64bfe674fa1dc2a90c043e6f0d7a22dbf7b2bbd397d1237a05b247e69e87bdb288b9337a2080a17b65b5",
          "sha256": "d5c25e9478453d7aaa434f6d69c03ad6c0857cd851003d7d33231f104161bede",
          "sha1": "6cfe7a065f203274f0b7b27c3894e9185bd13ec9",
          "md5": "78ae8cd7d70ccb8500f2db6fe7c8c373"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.3.72"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tuprolog",
          "module": "2p301"
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.jar",
          "url": "plugin-1.0.jar",
          "size": 40294,
          "sha512": "70124f3e7799260e93bab423bc0a9fa318276204da9e64bfe674fa1dc2a90c043e6f0d7a22dbf7b2bbd397d1237a05b247e69e87bdb288b9337a2080a17b65b5",
          "sha256": "d5c25e9478453d7aaa434f6d69c03ad6c0857cd851003d7d33231f104161bede",
          "sha1": "6cfe7a065f203274f0b7b27c3894e9185bd13ec9",
          "md5": "78ae8cd7d70ccb8500f2db6fe7c8c373"
        }
      ]
    }
  ]
}
