{
  "formatVersion": "1.1",
  "component": {
    "group": "unibo.disi",
    "module": "plugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "umjazg4jtvg4roj4nrtwwotagq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.jar",
          "url": "plugin-1.0.jar",
          "size": 37148,
          "sha512": "f62b51d35f50da7056a59fa82859ad88404c19b0414e4093e1e21d1ff4f6e06917a58ed669030c435fccef957fca162234b066c0a8048bcd0f73c1c511b0d5fa",
          "sha256": "75bd580be58c57a57c4d21f56db276183b5e80aa924f1f2962325dead922f4ac",
          "sha1": "b15401e9b38c4c5ae58542ad3a060bf86bbdcc6f",
          "md5": "706cba8d74bcbf583158fd2d076645c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.3.72"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tuprolog",
          "module": "2p301"
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.jar",
          "url": "plugin-1.0.jar",
          "size": 37148,
          "sha512": "f62b51d35f50da7056a59fa82859ad88404c19b0414e4093e1e21d1ff4f6e06917a58ed669030c435fccef957fca162234b066c0a8048bcd0f73c1c511b0d5fa",
          "sha256": "75bd580be58c57a57c4d21f56db276183b5e80aa924f1f2962325dead922f4ac",
          "sha1": "b15401e9b38c4c5ae58542ad3a060bf86bbdcc6f",
          "md5": "706cba8d74bcbf583158fd2d076645c4"
        }
      ]
    }
  ]
}
