{
  "formatVersion": "1.1",
  "component": {
    "group": "unibo.disi",
    "module": "plugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tovaqgk7ubcl3eau34sxcugtcu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.jar",
          "url": "plugin-1.0.jar",
          "size": 20364,
          "sha512": "b5d80b03f44aaa66b36721b8aeb8c2de0825974f2f49697544edf934239eda3a6188697c7a25635a83284ff6603a2fa56d8970d62f024c366de2889c3ab09937",
          "sha256": "4b7f3d386136dae8d6471f63ee345b056ae396aa00b6ff77007c3eaf9e015593",
          "sha1": "3c3da6fe2346e123812d87a8bb2a34bf3313b1ad",
          "md5": "ebfa08dfb242d70cc83b6b933856ca0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.3.72"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tuprolog",
          "module": "2p301"
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.jar",
          "url": "plugin-1.0.jar",
          "size": 20364,
          "sha512": "b5d80b03f44aaa66b36721b8aeb8c2de0825974f2f49697544edf934239eda3a6188697c7a25635a83284ff6603a2fa56d8970d62f024c366de2889c3ab09937",
          "sha256": "4b7f3d386136dae8d6471f63ee345b056ae396aa00b6ff77007c3eaf9e015593",
          "sha1": "3c3da6fe2346e123812d87a8bb2a34bf3313b1ad",
          "md5": "ebfa08dfb242d70cc83b6b933856ca0b"
        }
      ]
    }
  ]
}
