/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package it.unibo.virtualrobotclient

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }

    fun xxx(){
        println("xxx")
    }
}

fun main(args: Array<String>) {
    println(App().greeting)
    App().xxx()
}
