version: '3'
services:
  wenv:
    image: docker.io/natbodocker/virtualrobotdisi:1.0
    ports:
      - 8090:8090
      - 8091:8091
  vrobotcontrol:
    image: virtualrobotcontrol:1.0
    ports:
      - 3001:3001
      - 3000:3000
    depends_on:
      - wenv

    ##    vrobotclient:
    ##      image: docker.io/natbodocker/usingvirtualrobot:1.0
    ##          depends_on:
    ##            - wenv


## -------------------------------------------------------------
## TODO See https://docs.docker.com/compose/startup-order/
## Compose does not wait until a container is “ready” (whatever that means for your particular application)
## - only until it’s running. There’s a good reason for this.
## The best solution is to perform this check in your application code,
## -------------------------------------------------------------
## docker-compose run --service-ports wenv
## docker-compose run --service-ports vrobotclient  ATTIVA ANCHE wenv